# Generated by Django 6.0.7 on 2026-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_link_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='expired_at',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='link',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
