# Generated by Django 6.0.7 on 2026-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_rename_expired_at_link_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
