# Generated by Django 6.0.7 on 2026-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_alter_link_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.CharField(),
        ),
    ]
