# Generated by Django 6.0.7 on 2026-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_alter_link_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
    ]
