# Generated by Django 6.0.7 on 2026-07-23 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0007_alter_link_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 25, 17, 34, 30, 983141, tzinfo=datetime.timezone.utc)),
        ),
    ]
